/**
 * Login page constants
 */

export const ACTION_LOGIN_REQUEST = "ACTION_LOGIN_REQUEST";
export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS';
export const ACTION_LOGIN_FAILURE = 'ACTION_LOGIN_FAILURE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const CLICKED_ROW = 'CLICKED_ROW';
export const SELECT_FILE = 'SELECT_FILE';
export const RECEIVE_EMPLOYEES = 'RECEIVE_EMPLOYEES';
export const RECEIVE_ROW_ID = 'RECEIVE_ROW_ID';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const CANCEL_EDIT_EMPLOYEE = "CANCEL_EDIT_EMPLOYEE";
export const SAVE_EMPLOYEE_POST = 'SAVE_EMPLOYEE_POST';
export const SAVE_EMPLOYEE_PUT = 'SAVE_EMPLOYEE_PUT';
export const EDIT_EMPLOYEE_VALUE = 'EDIT_EMPLOYEE_VALUE';
export const STORE_UPLOADED_PIC_NAME = 'STORE_UPLOADED_PIC_NAME';
export const PUT_SELECTED_FILE_IN_STORE = 'PUT_SELECTED_FILE_IN_STORE';
export const TAKE_UI_SNAPSHOT = 'TAKE_UI_SNAPSHOT';

//openings consts

export const FETCH_OPENINGS = 'FETCH_OPENINGS';
export const RECEIVE_OPENINGS = 'RECEIVE_OPENINGS';
export const DELETE_OPENING = 'DELETE_OPENING';
export const EDIT_OPENING = 'EDIT_OPENING';
export const CANCEL_OPENINGS = 'CANCEL_OPENINGS';
export const SAVE_OPENINGS_PUT = 'SAVE_OPENINGS_PUT';
export const SAVE_OPENINGS_POST = 'SAVE_OPENINGS_POST';
export const ADD_OPENING = 'ADD_OPENING';
export const EDIT_OPENING_VALUE = 'EDIT_OPENING_VALUE';
export const CANCEL_EDIT_OPENING = 'CANCEL_EDIT_OPENING';
